# Numpy 연습문제

## Numpy 개요
- `Numpy`는 C언어로 구현된 파이썬 라이브러리로써, 고성능의 수치계산을 위해 제작됨
- Numerical Python의 줄임말이기도 한 `Numpy`는 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공
- 데이터분석을 할 때 사용되는 라이브러리인 `pandas`와 `matplotlib`의 기반으로 사용되기도 함


In [3]:
# numpy 패키지 불러오기
import numpy as np

### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.
- `.zeros()`: 0으로 가득 찬 array를 생성(`.ones()`는 1로 가득 찬 array)

In [4]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

```
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])
```

- `.shape()`: 동적으로 할당된 array 에 대해서 몇행, 몇열 행렬로 구성되었는지 알아야 할 경우 사용(각 차원의 크기를 튜플로 표시)

In [9]:
# 방법 1
for i in range(a.shape[0]): # a.shape[0]: a의 행 개수(3)
    for j in range(a.shape[1]): # a.shape[1]: a의 열 개수(4)
        a[i, j] = i*4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [8]:
# 방법 2
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.
- 행렬 조작: a[0,0]부터 시작

In [24]:
# 2행 3열 추출
a[1, 2]

7.0

### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

`array([[5., 6., 7., 8.]])`


In [28]:
# a의 차원 확인
a.shape

(3, 4)

In [26]:
# 2행의 모든 데이터 출력
a[[1], :]

array([[5., 6., 7., 8.]])

In [30]:
# 차원 확인
a[[1], :].shape

(1, 4)

### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

```
array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])
```

In [32]:
# 인덱싱으로 2,3열 지정. 모든 행 출력
a[:,[1, 2]]

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

```
array([1., 2., 3., 4., 5., 6.])
```
- `.asarray()`: 배열의 참조본(전체 뷰)을 생성(복사 x)

In [33]:
# 방법 1. 배열을 생성하면서 if문으로 조작
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result

array([1., 2., 3., 4., 5., 6.])

In [34]:
# 방법 2. a에서 직접 인덱싱
a[a <= 6]

array([1., 2., 3., 4., 5., 6.])

### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.
- `.random.random(차원)`: 입력한 차원크기만큼 0에서 1 사이의 수를 채워서 반환 

In [36]:
# 3x4 크기의, 0~1값이 들어간 ndarray 생성
b = np.random.random((3, 4))
b

array([[0.21119023, 0.89018892, 0.63791831, 0.81102655],
       [0.65470241, 0.81862786, 0.5419361 , 0.64080217],
       [0.57998333, 0.27751374, 0.63720311, 0.93032924]])

### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [37]:
# 차원의 형태가 완전 일치하므로 a*b 사용
c = a * b
c

array([[ 0.21119023,  1.78037784,  1.91375494,  3.24410621],
       [ 3.27351206,  4.91176718,  3.79355267,  5.12641734],
       [ 5.21985   ,  2.77513741,  7.00923418, 11.16395088]])

### 9. b의 전치행렬을 구하여 d에 저장하시오.
- 전치행렬: 행렬의 행과 열을 바꾼 행렬

- Numpy에서는 다음 세 가지 method로 전치행렬을 구할 수 있음
 1.  b.T attribute

 2. np.transpose(b) method

 3. np.swapaxes(b, 0, 1) method




In [38]:
# b의 전치행렬을 d에 저장 후 출력
d = b.T
d

array([[0.21119023, 0.65470241, 0.57998333],
       [0.89018892, 0.81862786, 0.27751374],
       [0.63791831, 0.5419361 , 0.63720311],
       [0.81102655, 0.64080217, 0.93032924]])

In [39]:
# d의 차원 확인
d.shape

(4, 3)

### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [15]:
print(a.shape, d.shape)

(3, 4) (4, 3)


### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.
- `.dot()`: 내적곱을 구하는 함수. 행렬곱으로 사용하려면 첫번째 행렬의 열크기와 두번째 행렬의 행크기가 서로 같아야함

In [40]:
# 첫 번째 행렬(a) * 두 번째 행렬(d)
e = a.dot(d)
e

array([[ 7.14942922,  6.4809751 ,  6.7679371 ],
       [17.3507253 , 17.10524926, 16.46805478],
       [27.55202138, 27.72952342, 26.16817247]])

### 12. e에 대하여 각 열의 합을 계산하시오.
- `.sum()`: 행렬의 각 요소를 더하는 함수. `axis`로 축 옵션 조정

In [42]:
# e의 각 행에 대해 sum
np.sum(e, axis=1)

array([20.39834142, 50.92402935, 81.44971727])